### ISSUE TITLE
Sidekick running longer for 3-4 hours and crashing

### ISSUE THREAD

**Issue by asaini2804** [andreasjongenburger/power-bi-sidekick#2] opened 2023-05-04 12:31 UTC
Hello Andreas,

I'm having around 15 pbix files in a local folder which are connected to a single Power BI dataset Online (service). When I'm trying to analyze all the pbix files in a single go using Power BI sidekick , I'm getting either "Evaluating..."  or "Waiting of other queries" screen for hours (3-4 hrs) and after long period waiting time , my machine automatically crashes and restart itself and all applications running on my machine are gone , which means need to  again start from zero. 

![image](https://user-images.githubusercontent.com/132575488/236203874-0ce618bd-620c-4716-b7e0-792028fc55d4.png)

Dataset size and other info are here 

![image](https://user-images.githubusercontent.com/132575488/236204705-e079e0f1-eba3-4d43-9864-3b5c5c21766d.png)

My laptop is having 16 GB RAM and CPU + RAM consumptions are pretty high during above analysis.

Please recommend how to proceed!

Regards,
Amit

**Comment by andreasjongenburger** [comment] 2023-06-05 09:37
Hi Amit, 
great to see you are using Sidekick, unfortunately not succesful yet.

I'd expect 16GB should be sufficient. Even on the biggest models I have worked with, it only takes a few minutes to run as long as you have all your files stored locally. 

Have you also downloaded the dataset file and stored locally with the other report files?
If not, please try that first and always run Sidekick from that dataset-file. 

Furthermore, you could also first run the Sidekick on that one file alone (option 1 in powershell script) and see how long that takes. And from this, add more reports for evaluation. 

Please let me know if this solves anything!

Best,
Andreas

**Comment by asaini2804** [comment] 2023-06-06 07:10
Dear Andreas,

Thanks for your inputs!

Let me explain here better on what I’m trying to achieve.

Project Info : We are having a single PBI Dataset with below details and on top of it with live connection , we have developed around 17-18 Power BI reports and these reports as Power BI App has been published as one single product for the business. Mainly each Power BI report here talks about one of the Finance KPI like EBIT , CAPEX , CoCo etc.

***@***.***

We have separate workspace created of Power BI Dataset and Reports. Now , what I did for my analysis with Sidekick is to download all these PBIX files into a single folder on local machine (RAM 16 GB , Processor : Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz)  and with “option 1 in powershell script” , I’m trying to do the analysis. As I have mentioned before , this approach is not working.

Indeed, when I’m trying to analyze 1-2 pbix file with above approach , it is working the way expected within 1 min , but I need to do analysis for all the pbix files together to understand overall unused tables, fields , measures etc. etc. across this single product which end of the day connected to single PI dataset.

Download of dataset is not possible in our case because are not publishing the dataset to workspace using local machine, we are mainly using DevOps -XMLA approach to publish the dataset. Once the dataset has been touched by the XMLA endpoint, we are not allowed to download it anymore.

Please let me know how should I proceed next?

Regards,
Amit

**Comment by andreasjongenburger** [comment] 2023-06-12 14:25
Hi Amit, 
thanks for the elaboration. From that I get the idea that you are using an old version, since the combination of XMLA-connection to the dataset combined with multiple files locally is not possible anymore in the powershell walk-through in  the "new" version.

Apart from that some slow-loading-issues have been solved in the December 2022 version, which might solve your problem.

Technically it is still possible, but it is a bit tricky to advice from this place.
Could you please send me a PM in LinkedIn, maybe we can set up a quick call so I can help out in a quick session.

Best,
Andreas

**Comment by asaini2804** [comment] 2023-06-12 14:31
Hello Andreas,

Thanks for your response and insights!

Actually , I was also more in favor of scheduling online TEAMS call with you and checking from your prospective if it is working as expected or not.

Based on your availability this week , please give me 2-3 slots of yours in CET time zone and accordingly , I will be sending you official invite.

Let me know if you are fine with the above approach or any preferred way of connecting?

Best Regards,
Amit Saini

**Comment by asaini2804** [comment] 2023-06-19 14:50
Hello Andreas,

Can you please recommend when can we connect via TEAMS?

Regards,
Amit
From: Saini, Amit
Sent: Monday, 12 June 2023 16:31
To: andreasjongenburger/power-bi-sidekick ***@***.***>; andreasjongenburger/power-bi-sidekick ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [andreasjongenburger/power-bi-sidekick] Sidekick running longer for 3-4 hours and crashing (Issue #2)

Hello Andreas,

Thanks for your response and insights!

Actually , I was also more in favor of scheduling online TEAMS call with you and checking from your prospective if it is working as expected or not.

Based on your availability this week , please give me 2-3 slots of yours in CET time zone and accordingly , I will be sending you official invite.

Let me know if you are fine with the above approach or any preferred way of connecting?

Best Regards,
Amit Saini

**Comment by andreasjongenburger** [comment] 2023-06-20 12:55
Hi Amit, 

as requested please PM me at LinkedIn. 
I don't visit this site often and then we don't have to bother others with private appointments.

Best,
Andreas

**Comment by andreasjongenburger** [comment] 2023-09-25 13:30
Will close this item, since issue was not caused by Sidekick file.

**Closed as completed by andreasjongenburger** 2023-09-25 13:30 UTC
