### ISSUE TITLE
Measures with a / are shown incorrectly as broken references

### ISSUE THREAD

**Issue by Remko1981** [andreasjongenburger/power-bi-sidekick#4] opened 2023-06-08 20:13 UTC
Measures with a slash '/' are shown incorrectly as a broken reference on the broken references page.

**Broken references page:**
![afbeelding](https://github.com/andreasjongenburger/power-bi-sidekick/assets/24568503/8598c1a3-9aa0-4d41-a55b-a1a8cbe63a8e)

**Documentation page:**
![afbeelding](https://github.com/andreasjongenburger/power-bi-sidekick/assets/24568503/852b5251-a9c8-4aeb-b4bb-8fc2b68abe2b)

**Comment by andreasjongenburger** [comment] 2023-06-12 14:26
Thanks Remko for informing me. I'll try to fix it in the next version.

**Comment by andreasjongenburger** [comment] 2023-09-25 14:20
Hi @Remko1981,

unfortunately I was unable to reproduce this error. Everything goes fine, even with the exact same measure name as you provided above:
![image](https://github.com/andreasjongenburger/power-bi-sidekick/assets/30201838/28f6d79b-025e-4a22-9c34-9ef4a4cfd7d3)

See green icon on landing page, which tells no reference error is found:
![image](https://github.com/andreasjongenburger/power-bi-sidekick/assets/30201838/4b5f2079-d944-437c-a271-fb0ac2dc51f8)


Maybe it got fixed with some other changes I have made since the latest published version?

I try to share the newest version today or tomorrow. Could you please try again afterwards?
(I'll inform you when it is live)

Best,
Andreas

**Closed as completed** 2024-05-22 09:59 UTC
